DROP TABLE IF EXISTS DINING_REVIEWS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RESTAURANTS;

CREATE TABLE IF NOT EXISTS DINING_REVIEWS (
	ID Long NOT NULL AUTO_INCREMENT,
	username varchar(255) NOT NULL,
	RESTAURANT_ID Long NOT NULL,
	PEANUT_ALLERGY int,
	EGG_ALLERGY int,
	DAIRY_ALLERGY int,
	COMMENTARY varchar(255),
	STATUS varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
	ID Long NOT NULL AUTO_INCREMENT,
	DISPLAY_NAME varchar(255) NOT NULL UNIQUE,
	CITY varchar(255) NOT NULL,
	STATE varchar(255) NOT NULL,
	ZIP_CODE int NOT NULL,
	PEANUT_ALLERGIES Boolean NOT NULL,
	EGG_ALLERGIES Boolean NOT NULL,
	DAIRY_ALLERGIES Boolean NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RESTAURANTS (
	ID Long NOT NULL AUTO_INCREMENT,
	NAME varchar(255),
	ZIP_CODE int,
	OVERALL_SCORE int NOT NULL,
	PEANUT_ALLERGY int,
	EGG_ALLERGY int,
	DAIRY_ALLERGY int,
    PRIMARY KEY (ID)
);


INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('coolusername', 'San Jose', 'CA', 95110, true, false, true);

INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('anonymoususer', 'Sacramento', 'CA', 95624, false, true, true);

INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('plantguy', 'Seattle', 'CA', 98005, false, false, false);

INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('catmando', 'Reno', 'CA', 89501, true, false, true);

INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGIES, EGG_ALLERGIES, DAIRY_ALLERGIES)
VALUES ('rationalegal', 'San Jose', 'CA', 95110, true, true, true);




INSERT INTO RESTAURANTS (NAME, ZIP_CODE, OVERALL_SCORE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('McDougles', 98005, 4, 1, 5, 5);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, OVERALL_SCORE, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('Barnacle King', 95624, 2, 3, 1);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, OVERALL_SCORE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('Nguyen Dees', 98005, 3, 4, 4, 2);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, OVERALL_SCORE, PEANUT_ALLERGY, DAIRY_ALLERGY)
VALUES ('Enter n Exit', 89501, 3, 4, 3);

INSERT INTO RESTAURANTS (NAME, ZIP_CODE, OVERALL_SCORE, PEANUT_ALLERGY)
VALUES ('Maria Schedule', 95110, 2, 1);



INSERT INTO DINING_REVIEWS (username, RESTAURANT_ID, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY, COMMENTARY, STATUS)
VALUES ('catmando', 2, 5, 4, 4, 'Excellent burgers', 'pending');

INSERT INTO DINING_REVIEWS (username, RESTAURANT_ID, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY, COMMENTARY, STATUS)
VALUES ('catmando', 1, 5, 3, 4, 'Best fries', 'approved');

INSERT INTO DINING_REVIEWS (username, RESTAURANT_ID, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY, COMMENTARY, STATUS)
VALUES ('plantguy', 3, 1, 1, 1, 'I demanded free food and they didn''t give it to me', 'rejected');

INSERT INTO DINING_REVIEWS (username, RESTAURANT_ID, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY, COMMENTARY, STATUS)
VALUES ('rationalegal', 4, 5, 4, 2, 'Healthy and fresh for fast food', 'pending');

INSERT INTO DINING_REVIEWS (username, RESTAURANT_ID, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY, COMMENTARY, STATUS)
VALUES ('anonymoususer', 2, 3, 3, 3, 'Employees were terrible. Food decent', 'approved');








